#!/bin/bash

# Auto-Build Environment Setup for Physics Optimization
# Generated by Planner Agent

set -e

echo "========================================"
echo "Physics Optimization Development Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

PROJECT_ROOT="/home/k0/work/crossworld/main-cw"
cd "$PROJECT_ROOT"

# ============================================
# VERIFY RUST TOOLCHAIN
# ============================================

echo ""
echo "Checking Rust toolchain..."
if command -v cargo &> /dev/null; then
    echo -e "${GREEN}Cargo found:${NC} $(cargo --version)"
else
    echo -e "${RED}Cargo not found!${NC} Please install Rust via rustup"
    exit 1
fi

# ============================================
# BUILD PHYSICS CRATE
# ============================================

echo ""
echo "Building crossworld-physics crate..."
if cargo build -p crossworld-physics; then
    echo -e "${GREEN}Physics crate built successfully${NC}"
else
    echo -e "${RED}Failed to build physics crate${NC}"
    exit 1
fi

# ============================================
# RUN PHYSICS TESTS
# ============================================

echo ""
echo "Running physics tests..."
if cargo test -p crossworld-physics --no-fail-fast 2>&1 | tail -20; then
    echo -e "${GREEN}Physics tests passed${NC}"
else
    echo -e "${YELLOW}Some tests may have failed - check output above${NC}"
fi

# ============================================
# RUN BENCHMARKS (DRY RUN)
# ============================================

echo ""
echo "Checking benchmark compilation..."
if cargo bench --bench collision -p crossworld-physics -- --test 2>&1 | head -10; then
    echo -e "${GREEN}Benchmarks compile successfully${NC}"
else
    echo -e "${RED}Benchmarks failed to compile${NC}"
    exit 1
fi

# ============================================
# BUILD PROTO-GL
# ============================================

echo ""
echo "Building proto-gl application..."
if cargo build -p proto-gl; then
    echo -e "${GREEN}Proto-GL built successfully${NC}"
else
    echo -e "${RED}Failed to build proto-gl${NC}"
    exit 1
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Key Commands:"
echo "  Run tests:       cargo test -p crossworld-physics"
echo "  Run benchmarks:  cargo bench --bench collision -p crossworld-physics"
echo "  Run proto-gl:    cd crates/proto-gl && cargo run"
echo ""
echo "Files to Optimize:"
echo "  crates/physics/src/terrain/collider.rs      - VoxelTerrainCollider"
echo "  crates/physics/src/terrain/region_cache.rs  - RegionCollisionData"
echo "  crates/physics/src/terrain/active_region.rs - ActiveRegionTracker"
echo "  crates/physics/src/terrain/triangle_gen.rs  - Triangle generation"
echo ""
echo "Optimization Targets:"
echo "  1. Reduce allocations in update_triangle_bvh()"
echo "  2. Pre-cache triangles in RegionCollisionData"
echo "  3. Improve active region hysteresis"
echo "  4. Add #[inline] hints to hot functions"
echo ""
