/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_worldcube_free: (a: number, b: number) => void;
export const worldcube_new: (a: number, b: number, c: number) => number;
export const worldcube_generateFrame: (a: number) => number;
export const worldcube_setVoxelAtDepth: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const worldcube_removeVoxelAtDepth: (a: number, b: number, c: number, d: number, e: number) => void;
export const worldcube_exportToCSM: (a: number) => [number, number];
export const worldcube_root: (a: number) => [number, number];
export const worldcube_setRoot: (a: number, b: number, c: number) => [number, number];
export const __wbg_geometrydata_free: (a: number, b: number) => void;
export const geometrydata_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const geometrydata_new_with_uvs: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => number;
export const geometrydata_vertices: (a: number) => [number, number];
export const geometrydata_indices: (a: number) => [number, number];
export const geometrydata_normals: (a: number) => [number, number];
export const geometrydata_colors: (a: number) => [number, number];
export const geometrydata_uvs: (a: number) => [number, number];
export const geometrydata_materialIds: (a: number) => [number, number];
export const __wbg_networkclient_free: (a: number, b: number) => void;
export const networkclient_connect: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => any;
export const networkclient_send_position: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => void;
export const networkclient_send_chat: (a: number, b: number, c: number) => any;
export const __wbg_avatarengine_free: (a: number, b: number) => void;
export const avatarengine_new: () => number;
export const avatarengine_generate_avatar: (a: number, b: number, c: number) => number;
export const avatarengine_clear_cache: (a: number) => void;
export const avatarengine_cache_size: (a: number) => number;
export const avatarengine_set_voxel: (a: number, b: number, c: number, d: number, e: number) => void;
export const avatarengine_remove_voxel: (a: number, b: number, c: number, d: number) => void;
export const load_vox_from_bytes: (a: number, b: number, c: number, d: number) => [number, number, number];
export const init: () => void;
export const avatarengine_regenerate_mesh: (a: number, b: number, c: number) => number;
export const networkclient_new: () => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const closure25_externref_shim: (a: number, b: number, c: any) => void;
export const closure110_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
