#!/bin/bash

# Auto-Build Environment Setup for OpenSpec Migration
# Generated by Planner Agent

set -e

echo "========================================"
echo "OpenSpec to Auto-Claude Migration Task"
echo "========================================"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo ""
echo -e "${YELLOW}This is a documentation migration task.${NC}"
echo "No services to start."
echo ""

# ============================================
# VERIFY PREREQUISITES
# ============================================

echo "Checking prerequisites..."

# Check openspec source exists
if [ -d "openspec/changes" ]; then
    ACTIVE_CHANGES=$(ls openspec/changes | grep -v archive | wc -l)
    echo -e "${GREEN}✓${NC} Found $ACTIVE_CHANGES active OpenSpec changes to migrate"
else
    echo "ERROR: openspec/changes directory not found"
    exit 1
fi

# Check target directory exists
if [ -d ".auto-claude/specs" ]; then
    EXISTING_TASKS=$(ls -d .auto-claude/specs/0*/ 2>/dev/null | wc -l)
    echo -e "${GREEN}✓${NC} Found $EXISTING_TASKS existing auto-claude tasks"
else
    echo "ERROR: .auto-claude/specs directory not found"
    exit 1
fi

# Check python for JSON validation
if command -v python3 &> /dev/null; then
    echo -e "${GREEN}✓${NC} python3 available for JSON validation"
else
    echo "WARNING: python3 not found - JSON validation will fail"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Migration Overview:"
echo "  Source: openspec/changes/ ($ACTIVE_CHANGES active changes)"
echo "  Target: .auto-claude/specs/003-012/"
echo ""
echo "Changes to Migrate:"
echo "  - optimize-world-collision -> 003-world-collision-optimization"
echo "  - improve-renderer-quality -> 004-renderer-quality"
echo "  - implement-gpu-raytracer -> 005-gpu-raytracer"
echo "  - refactor-renderer-interface -> 006-renderer-interface"
echo "  - create-proto-gl-physics-viewer -> 007-proto-gl-viewer"
echo "  - create-bevy-physics-prototype -> 008-bevy-physics"
echo "  - create-bevy-voxel-editor -> 009-bevy-editor"
echo "  - add-fabric-model-generation -> 010-fabric-model"
echo "  - add-function-cube-type -> 011-function-cube"
echo "  - add-terrain-composite-collider -> 012-terrain-collider"
echo ""
echo "Partial Completion Changes:"
echo "  - optimize-world-collision (some phases complete)"
echo "  - improve-renderer-quality (some phases complete)"
echo "  - add-fabric-model-generation (most phases complete)"
echo "  - add-function-cube-type (phases 1-2 complete)"
echo ""
